log4cpp: include cstdarg instead of stdarg.h
This might fix a compile error with GCC 5.4 without --std=c++11:

/home/travis/build/orocos-toolchain/orocos_toolchain/log4cpp/src/StringUtil.cpp: In static member function ‘static std::__cxx11::string log4cpp::StringUtil::vform(const char*, __va_list_tag*)’:
/home/travis/build/orocos-toolchain/orocos_toolchain/log4cpp/src/StringUtil.cpp:47:36: error: ‘va_copy’ was not declared in this scope
             va_copy(args_copy, args);
                                    ^